fake_data:
  folder_path: ./data/pump
  num_files: 3

datalake:
  endpoint: localhost:9000
  bucket_name: iot-time-series
  folder_name: pump
  access_key: minio_access_key
  secret_key: minio_secret_key